### ISSUE TITLE
Понятность

### ISSUE THREAD

**Issue by Bolmazov** [yapalenov/AmazingHiring_React#7]
https://github.com/yapalenov/AmazingHiring_React/blob/5a48ef8db34251ab3f9e9b05c8c2a1cad42b801f/components/TableHeader/index.js#L17

Куда более нагляднее, чем уносить логику в css
```
{reverse 
  ? <div className='arrow-top'></div>
  : <div className='arrow-bottom'></div>}
```

**Comment by yapalenov** [comment]
Здесь, задумано выводить обе стрелочки, а вот их цвет должен меняться в зависимости от класса родителя. Или лучше переделать и выводить одну стрелку?
